datadog:
  apiKey: "99ff0fb1ea7215302a0338860fa9d373"
  appKey: "46a2b52041682068d03a8b49b152083b209141b5"
  site: "datadoghq.com"
  logs:
    enabled: true
  apm:
    enabled: true
  processAgent:
    enabled: true

agents:
  containers:
    agent:
      env:
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_PROCESS_AGENT_ENABLED
          value: "true"
