apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-config
  namespace: default
data:
  conf.yaml: |
    ## Basic Configuration
    logs_enabled: true

    ## Datadog API key
    api_key: 4aea663defe70dca9ed423429985710f

    ## Application key (optional)
    app_key: 46a2b52041682068d03a8b49b152083b209141b5

    ## Datadog site
    site: us5.datadoghq.com

    ## Remote configuration enabled
    DD_REMOTE_CONFIGURATION_ENABLED: true

    ## Set log level
    log_level: ERROR  # Change this to ERROR if you want to see fewer logs

    logs:
      - type: file
        path: /app/logs/flask.log
        service: flask-app
        source: python
        sourcecategory: sourcecode
