datadog:
  apiKey: 99ff0fb1ea7215302a0338860fa9d373
  appKey: 46a2b52041682068d03a8b49b152083b209141b5
  site: 'us5.datadoghq.com'
  logs:
    enabled: true
  confd:
    python.d:
      conf.yaml: |
        logs_enabled: true
        logs:
          - type: file
            path: /app/logs/flask.log
            service: flask-app
            source: python
            sourcecategory: sourcecode
