apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-recom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-recom
  template:
    metadata:
      labels:
        app: games-recom
    spec:
      containers:
      - name: games-recom
        image: gcr.io/ornate-genre-425416-q8/games-recom:v4
        ports:
        - containerPort: 8080
