apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-rec
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-rec
  template:
    metadata:
      labels:
        app: games-rec
    spec:
      containers:
      - name: games-rec
        image: gcr.io/ornate-genre-425416-q8/games-rec:latest
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
