apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-recom-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: games-recom-test
  template:
    metadata:
      labels:
        app: games-recom-test
    spec:
      containers:
      - name: games-recom-test
        image: gcr.io/ornate-genre-425416-q8/games-recom-test:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATADOG_ENV
          value: "production"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_TRACE_DEBUG
          value: "true"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_REMOTE_CONFIGURATION_ENABLED
          value: "false"
        - name: DD_AGENT_HOST
          value: "datadog-agent"  
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        - name: datadog-config
          mountPath: /etc/datadog-agent/conf.d/python.d
        - name: allowed-log-path
          mountPath: /var/log/datadog
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: datadog-config
        configMap:
          name: datadog-config
      - name: allowed-log-path
        emptyDir: {}  # Use emptyDir instead of hostPath

