apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-rec
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-rec
  template:
    metadata:
      labels:
        app: games-rec
    spec:
      containers:
      - name: games-rec
        image: gcr.io/ornate-genre-425416-q8/games-rec:latest
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "flask_app"
        - name: DD_VERSION
          value: "1.0.0"
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_TRACE_ANALYTICS_ENABLED
          value: "true"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
