apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-recomm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-recomm
  template:
    metadata:
      labels:
        app: games-recomm
    spec:
      containers:
      - name: games-recomm
        image: gcr.io/ornate-genre-425416-q8/games-recomm:v5
        ports:
        - containerPort: 8080
