apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-reco-test
  labels:
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: games-reco-test
    tags.datadoghq.com/version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-reco-test
  template:
    metadata:
      labels:
        app: games-reco-test
        tags.datadoghq.com/env: production
        tags.datadoghq.com/service: games-reco-test
        tags.datadoghq.com/version: v1
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v2.9.2
    spec:
      containers:
      - name: games-reco-test
        image: gcr.io/ornate-genre-425416-q8/games-reco-test:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATADOG_ENV
          value: "production"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_TRACE_DEBUG
          value: "true"
        - name: DD_REMOTE_CONFIGURATION_ENABLED
          value: "true"
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
      volumes:
      - name: log-volume
        emptyDir: {}
