apiVersion: v1
kind: Service
metadata:
  name: games-recommendation-service
spec:
  type: LoadBalancer
  selector:
    app: games-recommendation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
