datadog:
  apiKey: 99ff0fb1ea7215302a0338860fa9d373
  appKey: 46a2b52041682068d03a8b49b152083b209141b5
  site: "datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    containerCollectUsingVolumes: true

  apm:
    enabled: true
    env: "production"
