datadog:
  apiKey: 99ff0fb1ea7215302a0338860fa9d373
  appKey: 46a2b52041682068d03a8b49b152083b209141b5
  site: "us5.datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    containerCollectUsingVolumes: true

  apm:
    enabled: true  # Ensure APM is enabled
    portEnabled: true
    env: "production"

  dogstatsd:
    enabled: true
    nonLocalTraffic: true
    port: 8125

  agent:
    env:
      - name: DD_REMOTE_CONFIGURATION_ENABLED
        value: "true"
      - name: DD_LOGS_INJECTION
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"

  containers:
    ports:
      - containerPort: 8126
        hostPort: 8126
        name: traceport
        protocol: TCP
      - containerPort: 8125
        hostPort: 8125
        name: dogstatsdport
        protocol: UDP
