datadog:
  apiKey: 99ff0fb1ea7215302a0338860fa9d373
  appKey: 46a2b52041682068d03a8b49b152083b209141b5
  site: "us5.datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    enabled: true
    portEnabled: true
    env: "production"

  dogstatsd:
    enabled: true
    nonLocalTraffic: true

  agent:
    image:
      repository: "gcr.io/datadoghq/agent"
      tag: "7.39.1"
    env:
      - name: DD_LOGS_INJECTION
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"
    volumeMounts:
      - name: datadog-config
        mountPath: /etc/datadog-agent/conf.d/python.d
    volumes:
      - name: datadog-config
        configMap:
          name: datadog-config

  daemonset:
    useHostPID: false
    useHostPort: false

  agents:
    trace:
      enabled: true
      port: 8126  # Make sure this port is not bound to the host
    process:
      enabled: true
      port: 8126  # Make sure this port is not bound to the host

  containers:
    - name: agent
      volumeMounts:
        - mountPath: /var/log/datadog
          name: allowed-log-path
    - name: trace-agent
      volumeMounts:
        - mountPath: /var/log/datadog
          name: allowed-log-path
    - name: process-agent
      volumeMounts:
        - mountPath: /var/log/datadog
          name: allowed-log-path

  volumes:
    - name: allowed-log-path
      hostPath:
        path: /var/log/datadog
    - name: datadog-config
      configMap:
        name: datadog-config
